name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: gradle
    - name: Replace the demo link
      run: sed -i 's/https:\/\/appassets.androidplatform.net\/assets\/webgal\/index.html/https:\/\/demo.openwebgal.com\//g' app/src/main/res/values/values.xml
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug apk
      run: ./gradlew assembleDebug
    - name: Rename debug apk
      run: mv app/build/outputs/apk/debug/app-debug.apk webgal-debug.apk
    - name: Upload debug apk
      uses: actions/upload-artifact@v4
      with:
        name: webgal-debug.apk
        path: webgal-debug.apk
  
  build-template-apk:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build template apk
      run: ./gradlew assembleRelease
    - name: Rename template apk
      run: mv app/build/outputs/apk/release/app-release-unsigned.apk webgal-template.apk
    - name: Upload template apk
      uses: actions/upload-artifact@v4
      with:
        name: webgal-template.apk
        path: webgal-template.apk

  release:
    runs-on: ubuntu-latest
    needs:
      - build-debug-apk
      - build-template-apk
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    - name: Create tag
      id: create_tag
      run: |
        echo "TAG_NAME=v$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false
        files: |
          artifacts/webgal-debug.apk
          artifacts/webgal-template.apk
